source 'https://rubygems.org'

gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-inspec'
gem 'inspec-bin'
gem 'berkshelf'
gem 'winrm'
gem 'winrm-fs'
gem 'vagrant-winrm'
gem 'kitchen-ansible'
gem 'inspec'
